FROM ubuntu:20.04


RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    curl \
    wget \
    git \
    vim \
    nano \
    build-essentials

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./app/app.py /app/app.py
COPY requirements.txt /app/requirements.txt
WORKDIR /app

RUN pip install -r requirements.txt

CMD ["python3", "app.py"]

